services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "6543:5432"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - db
    env_file:
      - .env
    command: sh -c "npx prisma migrate deploy && npm run start"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-data:
